version: "3"
services:
  nginx:
    ports:
      - "81:80"
  node-app:
    # build: .
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4300:3000"
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SECRET}
      # - MONGO_USER=cheks
      # - MONGO_PASS=mypassword
      # - SESSION_SECRET=secret
    command: node index.js

  mongo:
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=cheks
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
