version: "3"
services:
  nginx:
    ports:
      - "81:80"
  node-app:
    # build: .
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=cheks
      - MONGO_PASS=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cheks
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
